docs: add doxygen documentation in the Gui related files
MaximeHouis/YEP_project2_2019 pull request #16
Opened 2020-05-11 17:37 UTC by Perzi-Lgs

2020-05-11 18:22 UTC, rmaxi-me requested changes
The documentation could also use 3rd person singular conjugation.

2020-05-11 18:22 UTC, rmaxi-me commented on src/Engine/include/Engine/UI/AWidget.hpp
> +     * @param name The name of the widget, the name will be render
```suggestion
     * @param name The name of the widget, the name will be rendered
```

2020-05-11 18:22 UTC, rmaxi-me commented on src/Engine/include/Engine/UI/AWidget.hpp
> +     * @param size The szie of the widget
```suggestion
     * @param size The size of the widget
```

2020-05-11 18:22 UTC, rmaxi-me commented on src/Engine/include/Engine/UI/AWidget.hpp
> +     * @brief Set the Size object
```suggestion
     * @brief Set the size of the object
```

2020-05-11 18:22 UTC, rmaxi-me commented on src/Engine/include/Engine/UI/AWidget.hpp
> +     * @brief Set the Name object
```suggestion
     * @brief Set the name of the object
```

2020-05-11 18:22 UTC, rmaxi-me commented on src/Engine/include/Engine/UI/AWidget.hpp
> +     * @brief Get the Size object
```suggestion
     * @brief Get the size of the object
```

2020-05-11 18:22 UTC, rmaxi-me commented on src/Engine/include/Engine/UI/AWidget.hpp
> +     * @brief Get the Name object
```suggestion
     * @brief Get the name of the object
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/AWidget.hpp
> +     * @brief bind an action the widget will do when triggered
```suggestion
     * @brief bind an action to the widget
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/AWidget.hpp
> +     * @param std::function<void()> take an std::function to bind
```suggestion
     * @param std::function<void()> std::function to bind 
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @param name The name of the window, the name may be render
```suggestion
         * @param name The name of the window, the name may be rendered
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Set the Window Flags object
```suggestion
         * @brief Set the Window Flags
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Set the Position object
```suggestion
         * @brief Set the position of the object
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Set the Size object
```suggestion
         * @brief Set the size of the object
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Set the Name object
```suggestion
         * @brief Set the name of the object
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Get the Position object
```suggestion
         * @brief Get the position of the object
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Get the Size object
```suggestion
         * @brief Get the size of the object
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Get the Name object
```suggestion
         * @brief Get the name of the object
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Delete a widget store in the window
```suggestion
         * @brief Delete a widget stored in the window
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @return nullopt Return nullopt if the widget was not found
Something I didn't catch in the first PR, `std::optional` is not needed here because you could return `nullptr` for the exact same result.

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/UiWindow.hpp
> +         * @brief Delete a sub-window store in the window
```suggestion
         * @brief Delete a sub-window stored in the window
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/Widget/WButton.hpp
> +         * @brief Bind an action when to button is trigger
```suggestion
         * @brief Bind an action to the button
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/Widget/WButton.hpp
> +         * @brief Render the button and check if the it's triggered. If it is call the binded function
```suggestion
         * @brief Render the button and check if it's triggered. If it is, call the bound function
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/Widget/WMenuItem.hpp
> +             * @brief Bind an action when to menu item is trigger
```suggestion
             * @brief Bind an action to the menu item
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/Widget/WMenuItem.hpp
> +             * @brief Render the menu item and check if the it's triggered. If it is call the binded function
```suggestion
             * @brief Render the menu item and check if it's triggered. If it is, call the bound function
```

2020-05-11 18:22 UTC, MaximeHouis commented on src/Engine/include/Engine/UI/Window/MainMenuBar.hpp
> +     * @brief Main menu bar window class, create a main menu bar window int the top of the screen
```suggestion
     * @brief Main menu bar window class, create a main menu bar window on top of the screen
```

2020-05-11 22:02 UTC, Mathieu-Lala approved these changes

2020-05-12 13:45 UTC, rmaxi-me approved these changes

2020-05-12 14:06 UTC, merged